### ISSUE TITLE
Deploy to Azure results in error (Requested Tier for resource currently not available"

### ISSUE THREAD

**Issue by kumarrao** [EthereumEx/blockchain-060#3]
When I try to deploy to Azure, the deployment starts. After a few minutes it fails with the following error 
The requested tier for resource '/subscriptions/94f7474b-d024-43d0-ac57-d95b243b9d8a/resourceGroups/BC060RG/providers/Microsoft.Compute/virtualMachineScaleSets/b060-central-n-tx' is currently not available in location 'canadacentral' for subscription '94f7474b-d024-43d0-ac57-d95b243b9d8a'. Please try another tier or deploy to a different location.
Could you please let me know how to fix this? Thanks

**Comment by cicorias** [comment]
This is most likely a quota issue. Can you check the deployment details and drill into the specific error message reported by ARM? Go to the resource group and click in deployments at the top of the blade. Look through the granular log messages.

Also check the quota levels for your subscription in the portal by looking at the subscription blade. Quotas are mostly be region but some are also capped across region.

**Comment by kumarrao** [comment]
The specific deployment error is "SKU not found".  I checked the subscription quotas - in Canada Central. There seems to be room in all quota categories. For Virtual Machine Scale Sets in Canada Central it shows " of 2000". I assume it means I can use up to 2000 Scale Sets in Canada Central and have not used any?  
Thanks

**Comment by kumarrao** [comment]
I solved it by changing the EAST and CENTRAL miner nodes to West US2 (for some reason the SKU's in the deployment don't seem to exist in CanadaWest, CanadaCentral, EastUS, CentralUS...).
Thanks
